# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzYBklssNjRzyoc3meIStW5PK5ZXZudb

**Лабораторная работа №1**

Загрузка библиотек
"""

!pip install pandas numpy scikit-learn -q

import pandas as pd
import numpy as np
import sklearn.preprocessing as skl
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

"""Загрузка файла"""

df = pd.read_csv('/content/pima.dat', comment='@', header=None)

print(df.head())
print(df.info())

"""Здание 1-2

(выбор целевой переменной и подборта типов данных столбцов)
"""

df.columns = ['Preg', 'Plas', 'Pres', 'Skin', 'Insu', 'Mass', 'Pedi', 'Age', 'Class']

for col in df.columns[:-1]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Class'] = (df['Class'] == 'positive').astype(int)

print("Размер DataFrame:", df.shape)
print("\nПервые 5 строк:")
print(df.head())
print("\nИнформация о данных:")
print(df.info())
print("\nСтатистика:")
print(df.describe())
print("\nРаспределение классов:")
print(df['Class'].value_counts())

"""Задание 3

(Стандартизация)
"""

scaler = skl.StandardScaler()
df_scaled = df.copy()
df_scaled[df.columns[:-1]] = scaler.fit_transform(df[df.columns[:-1]])

print(df_scaled.head())

"""Задание 4

Разделите дата фрейм на обучающую, тестовую и валидационную выборки в
соотношении 5 / 3 / 2.
"""

from sklearn.model_selection import train_test_split

# Используем данные после стандартизации (df_scaled)
X = df_scaled.drop('Class', axis=1)
y = df_scaled['Class']

# Разделение 5/3/2
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.5, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.4, random_state=42)

print("Размеры выборок:")
print(f"Обучающая (50%): {X_train.shape}")
print(f"Тестовая (30%): {X_test.shape}")
print(f"Валидационная (20%): {X_val.shape}")

"""Задание 5

(На основе обучающей и тестовой выборки постройте дерево решений, рассчитайте
параметры эффективности классификатора (Accuracy, Precision, Recall, ROC-AUC).
Меняя значение параметра альфа ([0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.2, 0.8])
и критерий классификации ([Entropy, Gini]) подберите наиболее удачное по макро
усреднённому параметру ROC-AUC дерево классификации для подготовленных
выборок.)
"""

# Список параметров для перебора
alpha_values = [0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.2, 0.8]
criteria = ['entropy', 'gini']

# Список для хранения результатов
results = []

best_roc_auc = 0
best_params = {}
best_model = None

# Перебор параметров
for criterion in criteria:
    for alpha in alpha_values:
        # Создание и обучение модели
        dt = DecisionTreeClassifier(criterion=criterion, ccp_alpha=alpha, random_state=42)
        dt.fit(X_train, y_train)

        # Предсказания
        y_pred = dt.predict(X_test)
        y_proba = dt.predict_proba(X_test)[:, 1]

        # Метрики
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, zero_division=0)
        recall = recall_score(y_test, y_pred, zero_division=0)
        roc_auc = roc_auc_score(y_test, y_proba)

        # Сохраняем результаты
        results.append({
            'criterion': criterion,
            'alpha': alpha,
            'accuracy': round(accuracy, 4),
            'precision': round(precision, 4),
            'recall': round(recall, 4),
            'roc_auc': round(roc_auc, 4)
        })

        # Запоминаем лучшую модель по ROC-AUC
        if roc_auc > best_roc_auc:
            best_roc_auc = roc_auc
            best_params = {'criterion': criterion, 'alpha': alpha}
            best_model = dt

# Создаем DataFrame с результатами
results_df = pd.DataFrame(results)

# Выводим таблицу результатов
print("РЕЗУЛЬТАТЫ ПЕРЕБОРА ПАРАМЕТРОВ:")
print(results_df.to_string(index=False))

# Выводим лучшие параметры
print("ЛУЧШАЯ МОДЕЛЬ:")
print(f"criterion={best_params['criterion']}, alpha={best_params['alpha']:.3f}")
print(f"Лучший ROC-AUC: {best_roc_auc:.4f}")

# Оценка лучшей модели на тестовой выборке
y_pred_best = best_model.predict(X_test)
y_proba_best = best_model.predict_proba(X_test)[:, 1]

print("\nФИНАЛЬНЫЕ МЕТРИКИ ЛУЧШЕЙ МОДЕЛИ:")
final_metrics = pd.DataFrame([{
    'Accuracy': round(accuracy_score(y_test, y_pred_best), 4),
    'Precision': round(precision_score(y_test, y_pred_best, zero_division=0), 4),
    'Recall': round(recall_score(y_test, y_pred_best, zero_division=0), 4),
    'ROC-AUC': round(roc_auc_score(y_test, y_proba_best), 4)
}])
print(final_metrics.to_string(index=False))

# ВИЗУАЛИЗАЦИЯ ДЕРЕВА РЕШЕНИЙ
plt.figure(figsize=(20, 10))
plot_tree(best_model,
          feature_names=X_train.columns.tolist(),
          class_names=['negative', 'positive'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title(f"Дерево решений (criterion={best_params['criterion']}, alpha={best_params['alpha']})")
plt.show()

# Визуализация важности признаков
feature_importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': best_model.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['feature'], feature_importance['importance'])
plt.xlabel('Важность')
plt.title('Важность признаков в дереве решений')
plt.tight_layout()
plt.show()

"""Задание 6

На основе обучающей и тестовой выборки постройте SVM-классификатор,
рассчитайте параметры эффективности классификатора (Accuracy, Precision, Recall,
ROC-AUC). Меняя значение параметров kernel, gamma, coef0, degree, C (на основе
вариантов, представленных в лекции), обосновано подберите наиболее удачный
классификатор для подготовленных выборок.
"""

# Список параметров
params = [
    {'kernel': 'linear', 'C': [0.1, 1, 10]},
    {'kernel': 'rbf', 'C': [0.1, 1, 10], 'gamma': ['scale', 0.1, 1]},
    {'kernel': 'poly', 'C': [1, 10], 'degree': [2, 3], 'gamma': ['scale']}
]

results = []
best_roc_auc = 0
best_model = None
best_params = {}

print("Перебор параметров SVM:")

for p in params:
    kernel = p['kernel']
    for C in p['C']:
        if kernel == 'linear':
            svm = SVC(kernel='linear', C=C, probability=True, random_state=42)
            svm.fit(X_train, y_train)

            y_pred = svm.predict(X_test)
            y_proba = svm.predict_proba(X_test)[:, 1]

            roc_auc = roc_auc_score(y_test, y_proba)
            print(f"{kernel}, C={C}: ROC-AUC={roc_auc:.4f}")

            results.append([kernel, C, '-', '-', roc_auc])

            if roc_auc > best_roc_auc:
                best_roc_auc = roc_auc
                best_model = svm
                best_params = {'kernel': kernel, 'C': C}

        elif kernel == 'rbf':
            for gamma in p['gamma']:
                svm = SVC(kernel='rbf', C=C, gamma=gamma, probability=True, random_state=42)
                svm.fit(X_train, y_train)

                y_pred = svm.predict(X_test)
                y_proba = svm.predict_proba(X_test)[:, 1]

                roc_auc = roc_auc_score(y_test, y_proba)
                print(f"{kernel}, C={C}, gamma={gamma}: ROC-AUC={roc_auc:.4f}")

                results.append([kernel, C, gamma, '-', roc_auc])

                if roc_auc > best_roc_auc:
                    best_roc_auc = roc_auc
                    best_model = svm
                    best_params = {'kernel': kernel, 'C': C, 'gamma': gamma}

        elif kernel == 'poly':
            for degree in p['degree']:
                svm = SVC(kernel='poly', C=C, degree=degree, gamma='scale', probability=True, random_state=42)
                svm.fit(X_train, y_train)

                y_pred = svm.predict(X_test)
                y_proba = svm.predict_proba(X_test)[:, 1]

                roc_auc = roc_auc_score(y_test, y_proba)
                print(f"{kernel}, C={C}, degree={degree}: ROC-AUC={roc_auc:.4f}")

                results.append([kernel, C, degree, '-', roc_auc])

                if roc_auc > best_roc_auc:
                    best_roc_auc = roc_auc
                    best_model = svm
                    best_params = {'kernel': kernel, 'C': C, 'degree': degree}

# Результаты
results_df = pd.DataFrame(results, columns=['kernel', 'C', 'param', 'param2', 'roc_auc'])
print("\nЛучшие результаты:")
print(results_df.sort_values('roc_auc', ascending=False).head(10).to_string(index=False))

print(f"\nЛучшая модель: {best_params}")
print(f"ROC-AUC: {best_roc_auc:.4f}")

# Финальные метрики
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, zero_division=0):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.4f}")

"""Задание 7

На основе обучающей и тестовой выборки постройте Random Forest-классификатор.
Меняя значение параметра критерия классификации ([Entropy, Gini]), а также число
генерируемых деревьев и число используемых полей подберите наиболее удачный
по макро усреднённому параметру ROC-AUC лес для подготовленных выборок
"""

# Список параметров для перебора
criteria = ['entropy', 'gini']
n_estimators_list = [50, 100, 200]
max_features_list = ['sqrt', 'log2', None]

results = []
best_roc_auc = 0
best_model = None
best_params = {}

print("Перебор параметров Random Forest:")

for criterion in criteria:
    for n_estimators in n_estimators_list:
        for max_features in max_features_list:
            # Создание и обучение модели
            rf = RandomForestClassifier(
                n_estimators=n_estimators,
                criterion=criterion,
                max_features=max_features,
                random_state=42,
                n_jobs=-1
            )
            rf.fit(X_train, y_train)

            # Предсказания
            y_pred = rf.predict(X_test)
            y_proba = rf.predict_proba(X_test)[:, 1]

            # Метрики
            accuracy = accuracy_score(y_test, y_pred)
            precision = precision_score(y_test, y_pred, zero_division=0)
            recall = recall_score(y_test, y_pred, zero_division=0)
            roc_auc = roc_auc_score(y_test, y_proba)

            results.append({
                'criterion': criterion,
                'n_estimators': n_estimators,
                'max_features': max_features,
                'accuracy': round(accuracy, 4),
                'precision': round(precision, 4),
                'recall': round(recall, 4),
                'roc_auc': round(roc_auc, 4)
            })

            print(f"{criterion}, n={n_estimators}, f={max_features}: ROC-AUC={roc_auc:.4f}")

            if roc_auc > best_roc_auc:
                best_roc_auc = roc_auc
                best_model = rf
                best_params = {
                    'criterion': criterion,
                    'n_estimators': n_estimators,
                    'max_features': max_features
                }

# Результаты
results_df = pd.DataFrame(results)
print("ТОП-10 ЛУЧШИХ РЕЗУЛЬТАТОВ RANDOM FOREST:")
print(results_df.sort_values('roc_auc', ascending=False).head(10).to_string(index=False))

print("ЛУЧШАЯ МОДЕЛЬ RANDOM FOREST:")
print(f"Параметры: {best_params}")
print(f"ROC-AUC: {best_roc_auc:.4f}")

# Оценка лучшей модели
y_pred_best = best_model.predict(X_test)
y_proba_best = best_model.predict_proba(X_test)[:, 1]

print("\nФИНАЛЬНЫЕ МЕТРИКИ ЛУЧШЕЙ МОДЕЛИ:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_best):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_best, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_best, zero_division=0):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_proba_best):.4f}")

# Важность признаков
feature_importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': best_model.feature_importances_
}).sort_values('importance', ascending=False)

print("\nВАЖНОСТЬ ПРИЗНАКОВ:")
print(feature_importance.to_string(index=False))

# Визуализация важности признаков
plt.figure(figsize=(10, 6))
plt.barh(feature_importance['feature'], feature_importance['importance'])
plt.xlabel('Важность')
plt.title('Важность признаков в Random Forest')
plt.tight_layout()
plt.show()

"""Задание 8

Выполните обогащение выборки и повторите шаги 5, 6, 7. Выполните
стратификацию выборки и повторите шаги 5, 6, 7. Сравните с помощью метрик и
валидационной выборки, полученные классификаторы и выберите лучший.

Обогащение данных и выполнение шага 5,6,7
"""

# Функция обогащения (oversampling) с сохранением формата DataFrame
def oversample(X, y):
    # Преобразуем в numpy для обработки
    X_np = np.array(X)
    y_np = np.array(y)

    classes = np.unique(y_np)
    max_count = max(np.sum(y_np == c) for c in classes)

    X_aug = list(X_np)
    y_aug = list(y_np)

    for c in classes:
        indices = np.where(y_np == c)[0]
        current = len(indices)
        to_add = max_count - current

        if to_add > 0:
            add_indices = np.random.choice(indices, to_add, replace=True)
            for idx in add_indices:
                X_aug.append(X_np[idx])
                y_aug.append(c)

    # Преобразуем обратно в DataFrame с сохранением названий столбцов
    X_aug_df = pd.DataFrame(X_aug, columns=X.columns)
    y_aug_series = pd.Series(y_aug, name=y.name)

    return X_aug_df, y_aug_series

# Функция для вычисления метрик
def get_metrics(model, X, y):
    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)[:, 1]
    return {
        'Accuracy': round(accuracy_score(y, y_pred), 4),
        'Precision': round(precision_score(y, y_pred, zero_division=0), 4),
        'Recall': round(recall_score(y, y_pred, zero_division=0), 4),
        'ROC-AUC': round(roc_auc_score(y, y_proba), 4)
    }

# --- ОБОГАЩЕНИЕ ВЫБОРКИ ---
print("ОБОГАЩЕНИЕ ВЫБОРКИ")

# Разбиение данных (50/30/20)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.5, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.4, random_state=42)

print(f"Размер обучающей до обогащения: {len(X_train)}")
print(f"Распределение классов до: {np.bincount(y_train)}")

# Обогащаем обучающую выборку
X_train_over, y_train_over = oversample(X_train, y_train)

print(f"Размер обучающей после обогащения: {len(X_train_over)}")
print(f"Распределение классов после: {np.bincount(y_train_over)}")
print(f"Тип данных после обогащения: {type(X_train_over)}")
print(f"Названия столбцов сохранены: {list(X_train_over.columns)}")

# --- ПОВТОРЕНИЕ ШАГА 5: ДЕРЕВО РЕШЕНИЙ ---
print("ШАГ 5: ДЕРЕВО РЕШЕНИЙ")

# Параметры для перебора
alpha_values = [0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.2, 0.8]
criteria = ['entropy', 'gini']

best_dt_roc = 0
best_dt_params = {}
best_dt_model = None

for criterion in criteria:
    for alpha in alpha_values:
        dt = DecisionTreeClassifier(criterion=criterion, ccp_alpha=alpha, random_state=42)
        dt.fit(X_train_over, y_train_over)

        y_proba = dt.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)

        print(f"criterion={criterion}, alpha={alpha:.3f}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_dt_roc:
            best_dt_roc = roc_auc
            best_dt_params = {'criterion': criterion, 'alpha': alpha}
            best_dt_model = dt

print(f"\nЛучшая модель DT: {best_dt_params}, ROC-AUC={best_dt_roc:.4f}")
dt_metrics = get_metrics(best_dt_model, X_val, y_val)
print(f"На валидации: Accuracy={dt_metrics['Accuracy']}, Precision={dt_metrics['Precision']}, Recall={dt_metrics['Recall']}, ROC-AUC={dt_metrics['ROC-AUC']}")

# --- ПОВТОРЕНИЕ ШАГА 6: SVM ---
print("ШАГ 6: SVM")

# Параметры для SVM
kernels = ['linear', 'rbf', 'poly']
C_values = [0.1, 1, 10]
gamma_values = ['scale', 0.1, 1]
degree_values = [2, 3]

best_svm_roc = 0
best_svm_params = {}
best_svm_model = None

# Linear
for C in C_values:
    svm = SVC(kernel='linear', C=C, probability=True, random_state=42)
    svm.fit(X_train_over, y_train_over)
    y_proba = svm.predict_proba(X_test)[:, 1]
    roc_auc = roc_auc_score(y_test, y_proba)
    print(f"linear, C={C}: ROC-AUC={roc_auc:.4f}")

    if roc_auc > best_svm_roc:
        best_svm_roc = roc_auc
        best_svm_params = {'kernel': 'linear', 'C': C}
        best_svm_model = svm

# RBF
for C in C_values:
    for gamma in gamma_values:
        svm = SVC(kernel='rbf', C=C, gamma=gamma, probability=True, random_state=42)
        svm.fit(X_train_over, y_train_over)
        y_proba = svm.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)
        print(f"rbf, C={C}, gamma={gamma}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_svm_roc:
            best_svm_roc = roc_auc
            best_svm_params = {'kernel': 'rbf', 'C': C, 'gamma': gamma}
            best_svm_model = svm

# Poly
for C in C_values:
    for degree in degree_values:
        svm = SVC(kernel='poly', C=C, degree=degree, gamma='scale', probability=True, random_state=42)
        svm.fit(X_train_over, y_train_over)
        y_proba = svm.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)
        print(f"poly, C={C}, degree={degree}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_svm_roc:
            best_svm_roc = roc_auc
            best_svm_params = {'kernel': 'poly', 'C': C, 'degree': degree}
            best_svm_model = svm

print(f"\nЛучшая модель SVM: {best_svm_params}, ROC-AUC={best_svm_roc:.4f}")
svm_metrics = get_metrics(best_svm_model, X_val, y_val)
print(f"На валидации: Accuracy={svm_metrics['Accuracy']}, Precision={svm_metrics['Precision']}, Recall={svm_metrics['Recall']}, ROC-AUC={svm_metrics['ROC-AUC']}")

# --- ПОВТОРЕНИЕ ШАГА 7: RANDOM FOREST ---
print("ШАГ 7: RANDOM FOREST")

# Параметры для Random Forest
criteria = ['entropy', 'gini']
n_estimators_list = [50, 100, 200]
max_features_list = ['sqrt', 'log2', None]

best_rf_roc = 0
best_rf_params = {}
best_rf_model = None

for criterion in criteria:
    for n_estimators in n_estimators_list:
        for max_features in max_features_list:
            rf = RandomForestClassifier(
                n_estimators=n_estimators,
                criterion=criterion,
                max_features=max_features,
                random_state=42,
                n_jobs=-1
            )
            rf.fit(X_train_over, y_train_over)

            y_proba = rf.predict_proba(X_test)[:, 1]
            roc_auc = roc_auc_score(y_test, y_proba)

            print(f"{criterion}, n={n_estimators}, f={max_features}: ROC-AUC={roc_auc:.4f}")

            if roc_auc > best_rf_roc:
                best_rf_roc = roc_auc
                best_rf_params = {
                    'criterion': criterion,
                    'n_estimators': n_estimators,
                    'max_features': max_features
                }
                best_rf_model = rf

print(f"\nЛучшая модель RF: {best_rf_params}, ROC-AUC={best_rf_roc:.4f}")
rf_metrics = get_metrics(best_rf_model, X_val, y_val)
print(f"На валидации: Accuracy={rf_metrics['Accuracy']}, Precision={rf_metrics['Precision']}, Recall={rf_metrics['Recall']}, ROC-AUC={rf_metrics['ROC-AUC']}")

# --- СРАВНЕНИЕ РЕЗУЛЬТАТОВ ---
print("СРАВНЕНИЕ МОДЕЛЕЙ ПОСЛЕ ОБОГАЩЕНИЯ")


comparison = pd.DataFrame({
    'Модель': ['Дерево решений', 'SVM', 'Random Forest'],
    'Accuracy': [dt_metrics['Accuracy'], svm_metrics['Accuracy'], rf_metrics['Accuracy']],
    'Precision': [dt_metrics['Precision'], svm_metrics['Precision'], rf_metrics['Precision']],
    'Recall': [dt_metrics['Recall'], svm_metrics['Recall'], rf_metrics['Recall']],
    'ROC-AUC': [dt_metrics['ROC-AUC'], svm_metrics['ROC-AUC'], rf_metrics['ROC-AUC']]
})

print(comparison.to_string(index=False))

# Выбор лучшей модели
best_idx = comparison['ROC-AUC'].idxmax()
best_model_name = comparison.loc[best_idx, 'Модель']
best_roc = comparison.loc[best_idx, 'ROC-AUC']

print(f"Лучшая модель после обогащения: {best_model_name} с ROC-AUC = {best_roc:.4f}")

"""Визуализация дерева решений для обогащенных данных"""

plt.figure(figsize=(20, 10))
plot_tree(best_dt_model,  # используем существующее имя
          feature_names=X_train_strat.columns.tolist(),
          class_names=['negative', 'positive'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title(f"Дерево решений (стратифицированные данные)\n(criterion={best_dt_params['criterion']}, alpha={best_dt_params['alpha']})")
plt.show()

# Визуализация важности признаков для дерева решений (стратифицированные данные)
feature_importance_stratified = pd.DataFrame({
    'feature': X_train_strat.columns,
    'importance': best_dt_model.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance_stratified['feature'], feature_importance_stratified['importance'], color='skyblue')
plt.xlabel('Важность')
plt.title('Важность признаков в дереве решений (стратифицированные данные)')
plt.tight_layout()
plt.show()

print("\nВАЖНОСТЬ ПРИЗНАКОВ (ДЕРЕВО РЕШЕНИЙ, СТРАТИФИЦИРОВАННЫЕ ДАННЫЕ):")
print(feature_importance_stratified.to_string(index=False))

"""Стратификация выборки и повторение шагов 5,6,7"""

print("8. СТРАТИФИКАЦИЯ ВЫБОРКИ И ПОВТОРЕНИЕ ШАГОВ 5, 6, 7")

# Функция для вычисления метрик
def get_metrics(model, X, y):
    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)[:, 1]
    return {
        'Accuracy': round(accuracy_score(y, y_pred), 4),
        'Precision': round(precision_score(y, y_pred, zero_division=0), 4),
        'Recall': round(recall_score(y, y_pred, zero_division=0), 4),
        'ROC-AUC': round(roc_auc_score(y, y_proba), 4)
    }

# --- СТРАТИФИКАЦИЯ ВЫБОРКИ ---
print("СТРАТИФИКАЦИЯ ВЫБОРКИ")

# Стратифицированное разбиение (сохраняем пропорции классов)
X_train_strat, X_temp_strat, y_train_strat, y_temp_strat = train_test_split(
    X, y, test_size=0.5, random_state=42, stratify=y
)
X_test_strat, X_val_strat, y_test_strat, y_val_strat = train_test_split(
    X_temp_strat, y_temp_strat, test_size=0.4, random_state=42, stratify=y_temp_strat
)

print(f"Размер обучающей: {len(X_train_strat)}")
print(f"Размер тестовой: {len(X_test_strat)}")
print(f"Размер валидационной: {len(X_val_strat)}")
print(f"\nРаспределение классов в обучающей: {np.bincount(y_train_strat)}")
print(f"Распределение классов в тестовой: {np.bincount(y_test_strat)}")
print(f"Распределение классов в валидационной: {np.bincount(y_val_strat)}")

# --- ПОВТОРЕНИЕ ШАГА 5: ДЕРЕВО РЕШЕНИЙ ---
print("ШАГ 5: ДЕРЕВО РЕШЕНИЙ")

# Параметры для перебора
alpha_values = [0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.2, 0.8]
criteria = ['entropy', 'gini']

best_dt_roc = 0
best_dt_params = {}
best_dt_model = None

for criterion in criteria:
    for alpha in alpha_values:
        dt = DecisionTreeClassifier(criterion=criterion, ccp_alpha=alpha, random_state=42)
        dt.fit(X_train_strat, y_train_strat)

        y_proba = dt.predict_proba(X_test_strat)[:, 1]
        roc_auc = roc_auc_score(y_test_strat, y_proba)

        print(f"criterion={criterion}, alpha={alpha:.3f}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_dt_roc:
            best_dt_roc = roc_auc
            best_dt_params = {'criterion': criterion, 'alpha': alpha}
            best_dt_model = dt

print(f"\nЛучшая модель DT: {best_dt_params}, ROC-AUC={best_dt_roc:.4f}")
dt_metrics = get_metrics(best_dt_model, X_val_strat, y_val_strat)
print(f"На валидации: Accuracy={dt_metrics['Accuracy']}, Precision={dt_metrics['Precision']}, Recall={dt_metrics['Recall']}, ROC-AUC={dt_metrics['ROC-AUC']}")

# --- ПОВТОРЕНИЕ ШАГА 6: SVM ---
print("ШАГ 6: SVM")

# Параметры для SVM
kernels = ['linear', 'rbf', 'poly']
C_values = [0.1, 1, 10]
gamma_values = ['scale', 0.1, 1]
degree_values = [2, 3]

best_svm_roc = 0
best_svm_params = {}
best_svm_model = None

# Linear
for C in C_values:
    svm = SVC(kernel='linear', C=C, probability=True, random_state=42)
    svm.fit(X_train_strat, y_train_strat)
    y_proba = svm.predict_proba(X_test_strat)[:, 1]
    roc_auc = roc_auc_score(y_test_strat, y_proba)
    print(f"linear, C={C}: ROC-AUC={roc_auc:.4f}")

    if roc_auc > best_svm_roc:
        best_svm_roc = roc_auc
        best_svm_params = {'kernel': 'linear', 'C': C}
        best_svm_model = svm

# RBF
for C in C_values:
    for gamma in gamma_values:
        svm = SVC(kernel='rbf', C=C, gamma=gamma, probability=True, random_state=42)
        svm.fit(X_train_strat, y_train_strat)
        y_proba = svm.predict_proba(X_test_strat)[:, 1]
        roc_auc = roc_auc_score(y_test_strat, y_proba)
        print(f"rbf, C={C}, gamma={gamma}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_svm_roc:
            best_svm_roc = roc_auc
            best_svm_params = {'kernel': 'rbf', 'C': C, 'gamma': gamma}
            best_svm_model = svm

# Poly
for C in C_values:
    for degree in degree_values:
        svm = SVC(kernel='poly', C=C, degree=degree, gamma='scale', probability=True, random_state=42)
        svm.fit(X_train_strat, y_train_strat)
        y_proba = svm.predict_proba(X_test_strat)[:, 1]
        roc_auc = roc_auc_score(y_test_strat, y_proba)
        print(f"poly, C={C}, degree={degree}: ROC-AUC={roc_auc:.4f}")

        if roc_auc > best_svm_roc:
            best_svm_roc = roc_auc
            best_svm_params = {'kernel': 'poly', 'C': C, 'degree': degree}
            best_svm_model = svm

print(f"\nЛучшая модель SVM: {best_svm_params}, ROC-AUC={best_svm_roc:.4f}")
svm_metrics = get_metrics(best_svm_model, X_val_strat, y_val_strat)
print(f"На валидации: Accuracy={svm_metrics['Accuracy']}, Precision={svm_metrics['Precision']}, Recall={svm_metrics['Recall']}, ROC-AUC={svm_metrics['ROC-AUC']}")

# --- ПОВТОРЕНИЕ ШАГА 7: RANDOM FOREST ---
print("ШАГ 7: RANDOM FOREST")

# Параметры для Random Forest
criteria = ['entropy', 'gini']
n_estimators_list = [50, 100, 200]
max_features_list = ['sqrt', 'log2', None]

best_rf_roc = 0
best_rf_params = {}
best_rf_model = None

for criterion in criteria:
    for n_estimators in n_estimators_list:
        for max_features in max_features_list:
            rf = RandomForestClassifier(
                n_estimators=n_estimators,
                criterion=criterion,
                max_features=max_features,
                random_state=42,
                n_jobs=-1
            )
            rf.fit(X_train_strat, y_train_strat)

            y_proba = rf.predict_proba(X_test_strat)[:, 1]
            roc_auc = roc_auc_score(y_test_strat, y_proba)

            print(f"{criterion}, n={n_estimators}, f={max_features}: ROC-AUC={roc_auc:.4f}")

            if roc_auc > best_rf_roc:
                best_rf_roc = roc_auc
                best_rf_params = {
                    'criterion': criterion,
                    'n_estimators': n_estimators,
                    'max_features': max_features
                }
                best_rf_model = rf

print(f"\nЛучшая модель RF: {best_rf_params}, ROC-AUC={best_rf_roc:.4f}")
rf_metrics = get_metrics(best_rf_model, X_val_strat, y_val_strat)
print(f"На валидации: Accuracy={rf_metrics['Accuracy']}, Precision={rf_metrics['Precision']}, Recall={rf_metrics['Recall']}, ROC-AUC={rf_metrics['ROC-AUC']}")

# --- СРАВНЕНИЕ РЕЗУЛЬТАТОВ ПОСЛЕ СТРАТИФИКАЦИИ ---
print("СРАВНЕНИЕ МОДЕЛЕЙ ПОСЛЕ СТРАТИФИКАЦИИ")

comparison_strat = pd.DataFrame({
    'Модель': ['Дерево решений', 'SVM', 'Random Forest'],
    'Accuracy': [dt_metrics['Accuracy'], svm_metrics['Accuracy'], rf_metrics['Accuracy']],
    'Precision': [dt_metrics['Precision'], svm_metrics['Precision'], rf_metrics['Precision']],
    'Recall': [dt_metrics['Recall'], svm_metrics['Recall'], rf_metrics['Recall']],
    'ROC-AUC': [dt_metrics['ROC-AUC'], svm_metrics['ROC-AUC'], rf_metrics['ROC-AUC']]
})

print(comparison_strat.to_string(index=False))

# Выбор лучшей модели после стратификации
best_idx_strat = comparison_strat['ROC-AUC'].idxmax()
best_model_strat = comparison_strat.loc[best_idx_strat, 'Модель']
best_roc_strat = comparison_strat.loc[best_idx_strat, 'ROC-AUC']

print(f" Лучшая модель после стратификации: {best_model_strat} с ROC-AUC = {best_roc_strat:.4f}")

"""Визуализация дерева решений для стратификационных данных"""

# ВИЗУАЛИЗАЦИЯ ДЕРЕВА РЕШЕНИЙ ДЛЯ СТРАТИФИЦИРОВАННЫХ ДАННЫХ
plt.figure(figsize=(20, 10))
plot_tree(best_dt_model,  # используем существующее имя
          feature_names=X_train_strat.columns.tolist(),
          class_names=['negative', 'positive'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title(f"Дерево решений (стратифицированные данные)\n(criterion={best_dt_params['criterion']}, alpha={best_dt_params['alpha']})")
plt.show()

# Визуализация важности признаков для дерева решений (стратифицированные данные)
feature_importance_stratified = pd.DataFrame({
    'feature': X_train_strat.columns,
    'importance': best_dt_model.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance_stratified['feature'], feature_importance_stratified['importance'], color='skyblue')
plt.xlabel('Важность')
plt.title('Важность признаков в дереве решений (стратифицированные данные)')
plt.tight_layout()
plt.show()

print("\nВАЖНОСТЬ ПРИЗНАКОВ (ДЕРЕВО РЕШЕНИЙ, СТРАТИФИЦИРОВАННЫЕ ДАННЫЕ):")
print(feature_importance_stratified.to_string(index=False))

"""Сравнение с помощью метрик и валидационной выборки, полученных классификаторов и выбор лучших"""

# --- СОБИРАЕМ МЕТРИКИ С ИСХОДНЫХ ДАННЫХ ---
print("СБОР МЕТРИК С ИСХОДНЫХ ДАННЫХ")

# Функция для вычисления метрик (если еще не определена)
def get_metrics(model, X, y):
    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)[:, 1]
    return {
        'Accuracy': round(accuracy_score(y, y_pred), 4),
        'Precision': round(precision_score(y, y_pred, zero_division=0), 4),
        'Recall': round(recall_score(y, y_pred, zero_division=0), 4),
        'ROC-AUC': round(roc_auc_score(y, y_proba), 4)
    }

# Используем модели, которые уже обучены на исходных данных
# Дерево решений (из шага 5)
dt_metrics_original = get_metrics(best_model, X_val, y_val)
print(f"Исходные DT - ROC-AUC: {dt_metrics_original['ROC-AUC']}")

# SVM (из шага 6)
svm_metrics_original = get_metrics(best_svm_model, X_val, y_val)
print(f"Исходные SVM - ROC-AUC: {svm_metrics_original['ROC-AUC']}")

# Random Forest (из шага 7)
rf_metrics_original = get_metrics(best_rf_model, X_val, y_val)
print(f"Исходные RF - ROC-AUC: {rf_metrics_original['ROC-AUC']}")

# --- СРАВНЕНИЕ ВСЕХ МОДЕЛЕЙ ---
print("СРАВНЕНИЕ ВСЕХ МОДЕЛЕЙ (ПО МЕТРИКАМ НА ВАЛИДАЦИОННОЙ ВЫБОРКЕ)")

# Сводная таблица для ROC-AUC
roc_comparison = pd.DataFrame({
    'Модель': ['Дерево решений', 'SVM', 'Random Forest'],
    'Исходные данные': [
        dt_metrics_original['ROC-AUC'],
        svm_metrics_original['ROC-AUC'],
        rf_metrics_original['ROC-AUC']
    ],
    'Обогащенные данные': [
        dt_metrics['ROC-AUC'],
        svm_metrics['ROC-AUC'],
        rf_metrics['ROC-AUC']
    ],
    'Стратифицированные данные': [
        dt_metrics_strat['ROC-AUC'],
        svm_metrics_strat['ROC-AUC'],
        rf_metrics_strat['ROC-AUC']
    ]
})

print(roc_comparison.to_string(index=False))

# Поиск лучшей модели
best_roc = -1
best_model_name = ""
best_data_type = ""

for i, row in roc_comparison.iterrows():
    if row['Исходные данные'] > best_roc:
        best_roc = row['Исходные данные']
        best_model_name = row['Модель']
        best_data_type = 'исходных'

    if row['Обогащенные данные'] > best_roc:
        best_roc = row['Обогащенные данные']
        best_model_name = row['Модель']
        best_data_type = 'обогащенных'

    if row['Стратифицированные данные'] > best_roc:
        best_roc = row['Стратифицированные данные']
        best_model_name = row['Модель']
        best_data_type = 'стратифицированных'

print("\n" + "="*80)
print(f"Лучшая модель: {best_model_name} на {best_data_type} данных с ROC-AUC = {best_roc:.4f}")
print("="*80)

# Визуализация с осью Y от 0.6
plt.figure(figsize=(12, 6))
x = np.arange(len(roc_comparison['Модель']))
width = 0.25

bars1 = plt.bar(x - width, roc_comparison['Исходные данные'], width,
                label='Исходные данные', color='lightgray', edgecolor='black')
bars2 = plt.bar(x, roc_comparison['Обогащенные данные'], width,
                label='Обогащенные данные', color='skyblue', edgecolor='black')
bars3 = plt.bar(x + width, roc_comparison['Стратифицированные данные'], width,
                label='Стратифицированные данные', color='lightcoral', edgecolor='black')

plt.xlabel('Модель', fontsize=12)
plt.ylabel('ROC-AUC', fontsize=12)
plt.title('Сравнение моделей на разных типах данных', fontsize=14, fontweight='bold')
plt.xticks(x, roc_comparison['Модель'], fontsize=11)
plt.ylim(0.6, 0.9)  # Ось Y начинается с 0.6
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3, axis='y')

# Добавляем значения на столбцы
for bars in [bars1, bars2, bars3]:
    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                f'{height:.3f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()