# -*- coding: utf-8 -*-
"""ЛР2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dONPZ6YD_fZ0473m8eETYYrFhE422Q8d

Проверям в каком формате закодирован наш файлик(((
"""

!file -i /var/downloads/globalterrorismdb_0718dist.csv

"""Библиотеки"""

import pandas as pd
from sqlalchemy import create_engine
import psycopg2
import matplotlib.pyplot as plt
import numpy as np

"""Подключение к SQLке"""

DB_URL = "postgresql://postgres.bjxatsdwgpgdazldlfjb:G7D26pYDwHf0MqoO@aws-1-eu-west-2.pooler.supabase.com:5432/postgres"

conn = psycopg2.connect(DB_URL)
cur = conn.cursor()

import psycopg2

DB_URL = "postgresql://postgres.bjxatsdwgpgdazldlfjb:G7D26pYDwHf0MqoO@aws-1-eu-west-2.pooler.supabase.com:5432/postgres"

conn = psycopg2.connect(DB_URL)
cur = conn.cursor()
print("Свежее подключение создано")

cur.execute("DELETE FROM terrorist_attacks;")
conn.commit()
print("Все данные удалены из таблицы")

cur.execute("DROP TABLE IF EXISTS terrorist_attacks;")
conn.commit()
print("Старая таблица удалена")

cur.execute("DELETE FROM terrorist_attacks;")
conn.commit()
print("Все данные удалены из таблицы")

"""пункт а и b"""

df = pd.read_csv("/var/downloads/globalterrorismdb_0718dist.csv", encoding='iso-8859-1')
print(f" Файл прочитан. Строк: {len(df)}, колонок: {len(df.columns)}")
print("Колонки в файле:", df.columns.tolist()[:10])

# Оставляем только нужные колонки
df_filtered = df[['iyear', 'imonth', 'iday', 'country_txt', 'region_txt', 'latitude', 'longitude']].copy()

# Создаём поле accident_date
df_filtered['accident_date'] = pd.to_datetime(
    df_filtered['iyear'].astype(str) + '-' +
    df_filtered['imonth'].astype(str) + '-' +
    df_filtered['iday'].astype(str),
    errors='coerce'
)

print(f"Строк для загрузки: {len(df_filtered)}")
print("\nПервые 3 строки для проверки:")
print(df_filtered.head(3))

# Подключаемся через SQLAlchemy и загружаем в базу
engine = create_engine(DB_URL)
df_filtered.to_sql('terrorist_attacks', engine, if_exists='append', index=False)

"""Пункт с  (жестко очищаем данные)"""

# Пересоздаём курсор
cur = conn.cursor()

# строки до очистки
cur.execute("SELECT COUNT(*) FROM terrorist_attacks;")
before = cur.fetchone()[0]
print(f"До очистки: {before} строк")

# Удаляем строки
cur.execute("""
    DELETE FROM terrorist_attacks
    WHERE latitude IS NULL OR longitude IS NULL
       OR (latitude = 0 AND longitude = 0)
       OR country_txt IS NULL OR country_txt = '' OR country_txt = 'Unknown'
       OR region_txt IS NULL OR region_txt = ''
       OR accident_date IS NULL
       OR iyear < 1970 OR iyear > 2017
       OR imonth < 1 OR imonth > 12
       OR iday < 1 OR iday > 31
       OR (imonth = 2 AND iday > 29)
       OR (imonth IN (4,6,9,11) AND iday > 30)
       OR latitude < -90 OR latitude > 90
       OR longitude < -180 OR longitude > 180;
""")

removed = cur.rowcount
conn.commit()
print(f"Удалено строк: {removed}")

# Сколько строк ПОСЛЕ очистки
cur.execute("SELECT COUNT(*) FROM terrorist_attacks;")
after = cur.fetchone()[0]
print(f"После очистки: {after} строк")
print(f"Всего удалено: {before - after} строк")

"""Пункт d (жестко выполняем частотный анализ данных по переменной country_txt)"""

# Освежаем курсор
cur = conn.cursor()

# Частотный анализ по странам
cur.execute("""
    SELECT country_txt, COUNT(*) as attack_count
    FROM terrorist_attacks
    GROUP BY country_txt
    ORDER BY attack_count DESC;
""")

results = cur.fetchall()

print("Частотный анализ по странам (топ-15):")
for country, count in results[:15]:
    print(f"{country}: {count}")

print(f"\nВсего стран: {len(results)}")

"""Задание е (мб разобью потом еще на несколько частей)"""

# Освежаем курсор
cur = conn.cursor()

# Шаг 1. Удаляем страны с числом терактов < 5
cur.execute("""
    DELETE FROM terrorist_attacks
    WHERE country_txt IN (
        SELECT country_txt
        FROM terrorist_attacks
        GROUP BY country_txt
        HAVING COUNT(*) < 5
    );
""")
conn.commit()
print(f"Удалены страны с числом терактов < 5: {cur.rowcount} строк")

# Шаг 2. Получаем агрегированные данные по странам
cur.execute("""
    SELECT country_txt, COUNT(*) as cnt
    FROM terrorist_attacks
    GROUP BY country_txt
    ORDER BY cnt;
""")
country_data = cur.fetchall()

if len(country_data) < 10:
    print("Слишком мало стран для анализа")
else:
    countries = [row[0] for row in country_data]
    counts = [row[1] for row in country_data]

    total_range = max(counts) - min(counts)
    threshold_10 = total_range * 0.1
    print(f"Общий размах: {total_range}, 10% = {threshold_10:.2f}")

    n = len(counts)
    left_10_end = int(n * 0.1)
    right_10_start = int(n * 0.9)

    to_delete = set()

    # Шаг 3. Ищем разрыв в левой части
    for i in range(left_10_end - 1, 0, -1):
        diff = counts[i] - counts[i-1]
        if diff > threshold_10:
            print(f"Найден разрыв в левой части: {counts[i-1]} → {counts[i]} = {diff:.2f}")
            to_delete.update(countries[:i+1])
            break

    # Шаг 4. Ищем разрыв в правой части
    for i in range(right_10_start, n-1):
        diff = counts[i+1] - counts[i]
        if diff > threshold_10:
            print(f"Найден разрыв в правой части: {counts[i]} → {counts[i+1]} = {diff:.2f}")
            to_delete.update(countries[i+1:])
            break

    # Шаг 5. Удаляем найденные страны
    if to_delete:
        delete_list = list(to_delete)
        batch_size = 50
        for i in range(0, len(delete_list), batch_size):
            batch = delete_list[i:i+batch_size]
            placeholders = ','.join(['%s'] * len(batch))
            cur.execute(f"""
                DELETE FROM terrorist_attacks
                WHERE country_txt IN ({placeholders});
            """, batch)
        conn.commit()
        print(f"Удалено строк из экстремальных стран: {cur.rowcount}")
    else:
        print("Экстремальных стран не найдено")

# Шаг 6. Проверяем итоговое количество строк
cur.execute("SELECT COUNT(*) FROM terrorist_attacks;")
final_count = cur.fetchone()[0]
print(f"Всего строк после всех удалений: {final_count}")

"""f. Строим график зависимости общего числа террактов от календарного
месяца
"""

# Освежаем курсор
cur = conn.cursor()

# Получаем данные по месяцам
cur.execute("""
    SELECT imonth, COUNT(*) as attacks
    FROM terrorist_attacks
    WHERE imonth BETWEEN 1 AND 12
    GROUP BY imonth
    ORDER BY imonth;
""")

month_data = cur.fetchall()

months = []
attacks = []

for month, count in month_data:
    months.append(month)
    attacks.append(count)

# Построение графика
plt.figure(figsize=(10, 6))
plt.bar(months, attacks, color='skyblue', edgecolor='navy')
plt.xlabel('Месяц')
plt.ylabel('Количество терактов')
plt.title('Распределение терактов по месяцам')
plt.xticks(months, ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                    'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'])
plt.grid(axis='y', alpha=0.3)
plt.show()

print(f"Данные по месяцам:")
for month, count in month_data:
    print(f"Месяц {month}: {count} терактов")

"""g. На основе полученных данных проведите простейшее исследование наличия
факта корреляции между общим числом террактов и календарным месяцем.
"""

# Освежаем курсор
cur = conn.cursor()

# Получаем данные по месяцам
cur.execute("""
    SELECT imonth, COUNT(*) as attacks
    FROM terrorist_attacks
    WHERE imonth BETWEEN 1 AND 12
    GROUP BY imonth
    ORDER BY imonth;
""")

month_data = cur.fetchall()

months = []
attacks = []

for month, count in month_data:
    months.append(month)
    attacks.append(count)

# Визуальный анализ
plt.figure(figsize=(12, 5))

# График 1: Линейный график
plt.subplot(1, 2, 1)
plt.plot(months, attacks, 'o-', color='red', linewidth=2, markersize=8)
plt.xlabel('Месяц')
plt.ylabel('Количество терактов')
plt.title('Динамика терактов по месяцам')
plt.xticks(months, ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                    'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'])
plt.grid(alpha=0.3)

# График 2: Столбчатая диаграмма
plt.subplot(1, 2, 2)
plt.bar(months, attacks, color='skyblue', edgecolor='navy')
plt.xlabel('Месяц')
plt.ylabel('Количество терактов')
plt.title('Распределение терактов по месяцам')
plt.xticks(months, ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                    'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'])
plt.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# анализ по месяцам
print("\nСтатистика по месяцам:")
print("-" * 40)
for month, count in month_data:
    month_name = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                  'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][month-1]
    print(f"{month_name}: {count} терактов")

# минимум и максимум
min_attacks = min(attacks)
max_attacks = max(attacks)
min_month = months[attacks.index(min_attacks)]
max_month = months[attacks.index(max_attacks)]

min_month_name = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                  'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][min_month-1]
max_month_name = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                  'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][max_month-1]

print("\nАнализ:")
print(f"Минимум терактов: {min_month_name} ({min_attacks})")
print(f"Максимум терактов: {max_month_name} ({max_attacks})")
print(f"Размах: {max_attacks - min_attacks} терактов")

# Простая оценка сезонности
avg_attacks = sum(attacks) / len(attacks)
print(f"Среднемесячное число терактов: {avg_attacks:.1f}")

# Оценка отклонений
print("\nОтклонения от среднего:")
for month, count in month_data:
    month_name = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                  'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][month-1]
    deviation = count - avg_attacks
    sign = "+" if deviation > 0 else ""
    print(f"{month_name}: {sign}{deviation:.1f}")

# Вывод о наличии корреляции
print("\nВывод:")
if max_attacks - min_attacks < avg_attacks * 0.1:
    print("Колебания по месяцам незначительны, выраженной сезонности не наблюдается")
elif max_attacks - min_attacks < avg_attacks * 0.3:
    print("Наблюдается слабая сезонность с пиками в определенные месяцы")
else:
    print("Наблюдается выраженная сезонность: число терактов существенно меняется в зависимости от месяца")

# Полярная диаграмма для сезонности
angles = np.linspace(0, 2 * np.pi, len(months), endpoint=False).tolist()
angles += angles[:1]
attacks_cyclic = attacks + attacks[:1]

plt.figure(figsize=(8, 8))
ax = plt.subplot(111, projection='polar')
ax.plot(angles, attacks_cyclic, 'o-', linewidth=2, color='red')
ax.fill(angles, attacks_cyclic, alpha=0.3, color='orange')
ax.set_xticks(angles[:-1])
ax.set_xticklabels(['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                    'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'])
plt.title('Сезонность терактов (полярная диаграмма)', fontsize=14)
plt.show()

#Тепловая карта: распределение терактов по годам и месяцам
#Получаем данные для построения тепловой карты: количество терактов для каждого года и месяца
cur.execute("""
    SELECT iyear, imonth, COUNT(*) as cnt
    FROM terrorist_attacks
    GROUP BY iyear, imonth
    ORDER BY iyear, imonth;
""")
heat_data = cur.fetchall()

#Преобразуем в DataFrame для удобной сводки
import pandas as pd
import seaborn as sns

df_heat = pd.DataFrame(heat_data, columns=['year', 'month', 'count'])
# Строим сводную таблицу: годы по строкам, месяцы по столбцам
heat_pivot = df_heat.pivot(index='year', columns='month', values='count').fillna(0)

# Визуализация тепловой карты
plt.figure(figsize=(16, 10))
sns.heatmap(heat_pivot, annot=True, fmt='.0f', cmap='YlOrRd',
            linewidths=0.5, cbar_kws={'label': 'Количество терактов'})
plt.title('Тепловая карта терактов по годам и месяцам', fontsize=16)
plt.xlabel('Месяц', fontsize=12)
plt.ylabel('Год', fontsize=12)
plt.xticks(ticks=np.arange(12)+0.5, labels=['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                                            'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'])
plt.show()

print("Тепловая карта построена. Чем ярче цвет, тем больше терактов в данном месяце и году.")

# === Исследование корреляции между месяцем и числом терактов ===
# Для этого построим корреляционную матрицу между месяцами на основе
# многолетних данных. Это позволит выявить, существуют ли устойчивые
# связи между количеством терактов в разные месяцы.

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Получаем данные по годам и месяцам
cur.execute("""
    SELECT iyear, imonth, COUNT(*) as cnt
    FROM terrorist_attacks
    GROUP BY iyear, imonth
    ORDER BY iyear, imonth;
""")
data = cur.fetchall()

# Преобразуем в DataFrame
df = pd.DataFrame(data, columns=['year', 'month', 'count'])

# Строим сводную таблицу: годы → строки, месяцы → столбцы
pivot = df.pivot(index='year', columns='month', values='count').fillna(0)

# Вычисляем матрицу корреляций Пирсона между месяцами
corr = pivot.corr()

# Визуализация тепловой карты
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0,
            xticklabels=['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                         'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            yticklabels=['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
                         'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
            linewidths=0.5, cbar_kws={'label': 'Коэффициент корреляции'})
plt.title('Корреляция между месяцами по количеству терактов', fontsize=16)
plt.xlabel('Месяц')
plt.ylabel('Месяц')
plt.tight_layout()
plt.show()

# Анализ результатов
print("Тепловая карта корреляции между месяцами построена.")
print("Интерпретация:")
print("- Если большинство коэффициентов близки к 1, значит, все месяцы имеют схожую динамику (общий тренд).")
print("- Если выделяются блоки месяцев с высокой корреляцией внутри блока и низкой между блоками, это указывает на сезонность.")
print("- Отрицательные коэффициенты говорят о противоположных тенденциях в разные месяцы.")

# Дополнительно: рассчитаем корреляцию между номером месяца и суммарным числом терактов
monthly_total = df.groupby('month')['count'].sum().reset_index()
corr_month_total = monthly_total['month'].corr(monthly_total['count'])
print(f"\nКорреляция между номером месяца и общим числом терактов: {corr_month_total:.3f}")
if abs(corr_month_total) < 0.1:
    print("Связь практически отсутствует — нет линейной зависимости от месяца.")
elif corr_month_total > 0:
    print("Слабая положительная связь: к концу года терактов немного больше.")
else:
    print("Слабая отрицательная связь: в начале года терактов немного больше.")